spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: homeworkwithmongoDB
      username: homeworkwithmongoDB
      password: homework
      authentication-database: admin
